blank_issues_enabled: false
contact_links:
  - name: Documentation
    url: https://tyevans.github.io/eventsource-py
    about: Check our documentation for answers
  - name: Questions & Discussions
    url: https://github.com/tyevans/eventsource-py/discussions
    about: Ask questions and discuss ideas
